[[classification_module]]
name = "flu"
version = "2.0"
alternative_names = []
norm_score_minimum = 1.0
score_minimum = 100
length_minimum = 25
reference_sequences = "flu.fasta"
detect_chimera = true

[[classification_module]]
name = "cov"
version = "1.0"
alternative_names = ["cov-beta", "covid", "sc2"]
norm_score_minimum = 1.0
score_minimum = 100
length_minimum = 25
reference_sequences = "cov-beta.fasta"
detect_chimera = true

[[classification_module]]
name = "spike"
version = "1.0"
alternative_names = ["sc2-spike", "spike-sc2"]
norm_score_minimum = 0.7
score_minimum = 60
length_minimum = 25
reference_sequences = "spike-SC2.fasta"
detect_chimera = true

[[classification_module]]
name = "rsv"
version = "1.0"
alternative_names = []
norm_score_minimum = 1.0
score_minimum = 100
length_minimum = 25
reference_sequences = "rsv.fasta"
detect_chimera = false
